#+TITLE: 研究関連
#+DATE: 2017-10-30 13:39:50
#+LANGUAGE: ja
#+REF: research
#+LAYOUT: default
#+SETUPFILE: ../_setup.org
#+PERMALINK: /research/index.html
* 論文
** 査読有
   - _Sasaki, Y._, Takehiro, S.-I., Ishiwatari, M., Yamada, M., 2017:
     Effects of radial distribution of entropy diffusivity on critical modes of anelastic thermal convection in rotating spherical shells,
     hysics of the Earth and Planetary Interiors, =doi:10.1016/j.pepi.2017.09.003=
   - Takehiro, S-I., _Sasaki, Y._, 2017:
     Penetration of steady fluid motions into an outer stable layer excited by MHD thermal convection in rotating spherical shells,
     Physics of the Earth and Planetary Interiors,
     =doi: 10.1016/j.pepi.2017.03.001=
   - Matsui, H., Heien, E., Aubert, J., Aurnou, J.M., Avery, M., Brown, B., Buffett, B.A., Busse, F.H., Christensen, U.R., Davies, C.J., Featherstone, N., Gastine, T., Glatzmaier, G.A., Gubbins, D., Guermond, J.-L.,Hayashi, Y.-Y., Hollerbach, R., Hwang, R.J., Jackson, A., Jones, C.A., Jiang, W., Kellogg, L.H., Kuang, W., Landeau, M., Marti, P.H., Olson, P., Ribeiro, A., _Sasaki, Y._, Schaeffer, N., Simitev, R.D., Sheyko, A., Silva, L., Stanley, S., Takahashi, F., Takehiro, S.-I., Wicht, J., Willis, A.P., 2016:
     Performance benchmarks for a next generation numerical dynamo model,
     Geochemistry, Geophysics, Geosystem, =doi: 10.1002/2015GC006159=
   - Marti, P., Schaeffer, N., Hollerbach, R., Cebron, D., Nore, C., Luddens, F.,Guermond, J.-L., Aubert, J., Takehiro, S., _Sasaki, Y._, Hayashi, Y.-Y., Simitev, R., Busse, F., Vantieghem, S., Jackson, A., 2014:
     Full sphere hydrodynamic and dynamo benchmarks,
     Geophysical Journal International, 197, 119-134, =doi: 10.1093/gji/ggt518=
   - Takehiro, S., _Sasaki, Y._, Hayashi, Y.-Y., Yamada, M., 2013:
     Differential Rotation and Angular Momentum Transport Caused by Thermal Convection in a Rotating Spherical Shell,
     Progress in Physics of the Sun and Stars, 479, 285-294
   - Jackson, A. Sheyko, A., Marti, P., Tilgner, A., Cebron, D., Vantieghem, S., Simitev, R., Busse, F., Zhan, X., Schubert, G., Takehiro, S., Sasaki, Y., Hayashi, Y.-Y., Ribeiro, A., Nore, C., Guermondw, J.-L., 2013:
     A spherical shell numerical dynamo benchmark with pseudo-vacuum magnetic boundary conditions,
     Geophysical Journal International, 196, 712--723, =doi: 10.1093/gji/ggt425=
   - _Sasaki, Y._, Takehiro, S., Nishizawa, S., Hayashi, Y-Y., 2013:
     Effects of latitudinally heterogeneous buoyancy flux conditions at the inner core boundary of an MHD dynamo in a rotating spherical shell,
     Phys. Earth Planet. Inter., 223, 55-61, =doi:10.1016/j.pepi.2013.07.003=
   - Takehiro, S., Takahashi, Y.O., Sugiyama, K., Odaka, M., Ishiwatari, M., _Sasaki, Y._, Ishioka, K., Nishizawa, S., Nakajima, K., Hayashi, Y.-Y., 2012:
     Construction of Hierarchical Models for the Fluid Dynamics in Earth and Planetary Sciences : DCMODEL project.,
     In Proc. Inernational Conference on Simulation and Technology (JSST 2012), 301, Kobe, Japan, Sep. 27-28
   - _Sasaki, Y._, Takehiro, S., Nakajima, K., Hayashi, Y.-Y., 2012:
     Surface zonal flows induced by thermal convection in a rapidly rotating thin spherical shell,
     In Porc. Inernational Conference on Simulation and Technology (JSST 2012), 307, Kobe, Japan, Sep. 27-28
   - Ishiwatari, M., Toyoda, E., Morikawa, Y., Takehiro, S., _Sasaki, Y._, Nishizawa, S., Odaka, M., Otobe, N., Takahashi, Y. O., Nakajima, K., Horinouchi, T., Shiotani, M., Hayashi, Y.-Y., Gtool development group, 2012:
     gtool5 - development of Fortran90 library for self-descriptive multi-dimensional data input/output interfaces,
     Geosci. Model Dev., 5, 449-455., 2012, =doi:10.5194/gmd-5-449-2012=
   - _Sasaki, Y._, Takehiro, S., Hayashi, Y-Y., Kuramoto, K., 2011:
     Weak-field dynamo emerging in a rotating spherical shell with stress-free top and no-slip bottom boundaries.,
     Phys. Earth Planet. Inter., 188, 203--213., =doi:10.1016/j.pepi.2011.06.019=
** 査読無し
   - 竹広真一, 佐々木洋平, 石岡圭一, 2016:
     木星型惑星大気の縞状構造の成因の研究.
     平成 27 (2015) 年度地球シミュレータ利用報告書, pp.125--129.
   - 竹広真一, 佐々木洋平, 石岡圭一, 2014:
     木星型惑星大気の縞状構造の成因の研究.
     平成 26 (2014) 年度地球シミュレータ利用報告書
   - 佐々木 洋平, 竹広 真一, 中島健介, 林祥介, 2013:
     回転球殻内の非弾性流体熱対流の線形安定性,
     ながれ(日本流体力学会学会誌), 32, 469-472
   - 佐々木 洋平, 竹広 真一, 2011:
     熱フラックス固定境界条件下での回転球殻熱対流の線形安定性,
     ながれ 30 別冊, P. 57.
   - 竹広 真一, 佐々木 洋平, 西澤 誠也, 中島 健介, 林 祥介, 2011:
     回転球殻ダイナモに対する緯度方向不均一な内側浮力フラックス境界条件の影響,
     ながれ 30 別冊, P. 57.
   - 佐々木洋平, 竹広真一, 林祥介, 倉本圭, 2010:
     上端応力無し, 下端滑り無し条件を課した回転球殻中に出現する弱磁場ダイナモ,
     ながれ 29 別冊, 211
   - 佐々木洋平, 竹広真一, 林祥介, 倉本圭, 2009:
     回転球殻 MHD ダイナモ解に対する上部力学的境界条件の影響,
     ながれ 28 別冊, 106
   - 佐々木洋平, 竹広真一, 林祥介, 倉本 圭, 2008:
     回転球殻 MHD ダイナモにおける力学的境界条件の影響,
     ながれ, 27 別冊, 376.
   - 佐々木洋平, 竹広真一, 倉本圭, 林祥介, 2007:
     球殻の厚さを変えた回転球殻熱対流, ながれ, 26 別冊, 248.
   - 佐々木洋平, 小高正嗣, 竹広真一, 林祥介, 2004:
     ダイナモベンチマークにおける磁場生成維持機構の解析,
     ながれ, 23 別冊, 608-609
   - 佐々木洋平, 竹広真一, 林祥介, 2004:
     SPMODEL群の一環としての回転球殻MHD ダイナモの数値モデルの構築,
     ながれ, 22 別冊, 124-125
* 学会/研究集会発表
** 海外
   - _Sasaki, Y._, Takehiro, S.-I., Ishiwatari, M., Yamada, M., 2017:
     Effects of radial distribution of entropy diffusivity on critical modes of anelastic thermal convection in rotating spherical shells (numerical analysis)
     Compressible Convection Conference
   - _Sasaki, Y._, Takehiro, S.-I., Ishiwatari, M., Yamada, M., 2017:
     Rapidly rotating two-dimensional annulus model for anelastic critical thermal convection with tilting boundaries and radially varying entropy diffusivity
     Compressible Convection Conference
   - Takehiro, S., _Sasaki, Y._, 2017:
     Erosion of a thermally induced stably stratified layer by compositional convection in the Earth's outer core.
     AOGS 2017
   - Takehiro, S., _Sasaki, Y._, 2017:
     Erosion of a thermally induced stably stratified layer by compositional convection in the Earth's outer core,
     IAG-IASPEI 2017
   - Takehiro, S., _Sasaki, Y._, Ishioka, K., Nakajima, K., Hayashi, Y.-Y., 2017:
     Mean zonal flows induced by Boussinesq thermal convection in rotating spherical shells as an application to the gas giant planets.
     WTK Aquaplanet Workshop, 21st January 2017, National Astronomical Observatory of Japan.
   - Takehiro S., Takahashi, Y. O., Sugiyama, K., Odaka, M., Ishiwatari, M., Horinouchi, T., _Sasaki, Y._, Ishioka, K., Nakajima, K., Hayashi, Y.-Y., 2017:
     GFD-Dennou Club DCMODEL project.
     WTK Aquaplanet Workshop, 24th January 2017, CPS, Kobe University.
   - _Sasaki, Y._, Takehiro, S., Ishiwatari, M., Yamada, M., 2016:
     Critical mode of anelastic thermal convection in a rotating spherical shell depends on radial distribution of thermal diffusivity,
     SEDI The 15th Symposium, Nantes, France.
   - Takehiro, S., _Sasaki, Y._, 2016:
     Penetration of mean zonal flows into an outer stable layer excited by MHD thermal convection in rotating spherical shells,
     SEDI The 15th Symposium, Nantes, France.
   - Sasaki and Takehiro, S.-I. 2015:
     Penetration of magneto-hydrodynamic disturbances into a strongly stable outer layer caused by MHD dynamo in a rotating spherical shell,
     Japan SEDI symposium 2015.
   - Sasaki,Y., Takehiro, S. 2014,
     Penetration of magneto-hydrodynamic disturbances into an outer strongly stable layer caused by MHD dynamo in a rotating spherical shell,
     The 14th symposium of SEDI, Study of the Earth's Deep Interior, at the Shonan Village Center, Kanagawa, Japan, from August 3 to 8
   - Takehiro, S., Sasaki, Y., Takahashi, Y. O., Nakajima, K., Hayashi, Y.-Y., Kuramoto, K., 2013,
     Diversity of atmospheric circulations of sycronized rotating Jovian type planets.
     5th Subaru International Conference: Exoplanets and Disks:Their Formation and Diversity II,
     Dec. 8 to 12 2013, Sheraton Kona Resort & Spa Keauhou Bay, The Big island of Hawaii.
   - Sasaki, Y., Takehiro, S., Kuramoto, K., Hayashi, Y.-Y. 2013:
     Weak-field dynamo emerging in a rotating spherical shell with stress-free top and no-slip bottom boundaries,
     Mathematical analysis of magneto-hydrodynamical processes in stars, Sep. 26, 2013, Kansai Seminar House, Sakyo-ku, Kyoto, Japan.
   - Yoshiyuki O. Takahashi, Kouichirou Sugiyama, Masatsugu Odaka, Masaki Ishiwatari, _Youhei Sasaki_, Seiya Nishizawa, Kensuke Nakajima, Shin-ichi Takehiro, Yoshi-Yuki Hayashi, 2012
     Construction of Hierarchical Models for the Fluid Dynamics in Earth and Planetary Sciences : DCMODEL project,
     AGU Fall Meeting 2012, Dec 5th, 2012, San Francisco, California, USA.
   - _Sasaki, Y._, Takehiro, S., Nishizawa, S., Nakajima, K., Hayashi Y.-Y., 2012 :
     Effects of latitudinally heterogeneous buoyancy flux conditions at the inner boundary on MHD dynamos in a rotating spherical shell.
     The 13th Symposium of SEDI, Study of the Earth's Deep Interior, at the University of Leeds, UK, in Parkinson Court, from July 1 to 6
   - _Sasaki, Y._, Takehiro, S., Nakajima, K., Hayashi, Y.-Y., 2012:
     Development of an anelastic convection model in rotating spherical  shells for stars, gas and icy giant planets,
     The 13th Symposium of SEDI, Study of the Earth's Deep Interior, at the University of Leeds, UK, in Parkinson Court, from July 1 to 6
   - _Sasaki, Y._, Takehiro, S., Nishizawa, S., Nakajima, K., Hayashi, Y.-Y., 2012:
     Effects of latitudinally heterogeneous buoyancy flux conditions at the inner boundary on MHD dynamos in a rotating spherical shell,
     CPS 9th International School of Planetary Sciences.
   - _Sasaki, Y._, Takehiro, S., Nakajima, K., Kuramoto, K., Hayashi, Y.-Y., 2012:
     Development of an anelastic convection model in rotating spherical  shells for stars, gas and icy giant planets,
     CPS 9th International School of Planetary Sciences.
   - Ishiwatari1, M., K. Ishioka, S.-I. Takehiro, Y.-Y. Hayashi, S. Nishizawa, Y. O. Takahashi, M. Odaka, _Y. Sasaki_, K.-I. Sugiyama, T. Yamashita, Y. Morikawa, K. Nakajima, and GFD Dennou Club, 2010:
     DCMODEL: Hierarchical models for geophysical fluid dynamics and planetary atmospheres.
     CPS 6th International School of Planetary Sciences, P-18, 4-9 January, 2010, Kobe, Japan
   - _Sasaki, Y._, Takehiro, S., Kuramoto, K., Hayashi, Y.-Y., 2011:
     Weak-field dynamo emerging in a rotating spherical shell with stress-free top and no-slip bottom boundaries,
     AGU Fall Meeting 2011, Dec. 5th, 2011, San Francisco, California, USA.
   - _Sasaki, Y._, Takehiro, S., Hayashi, Y-Y., Kuramoto, K., 2011:
     Weak-field dynamo emerging in a rotating spherical shell with stress-free top and no-slip bottom boundaries,
     CPS 7th International School of Planetary Sciences, at Seapal Suma, Kobe, Japan, from January 10 to 15, 2011.
   - _Sasaki, Y._, Takehiro, S., Hayashi, Y-Y., Kuramoto, K., 2010:
     Weak-field dynamo emerging in a rotating spherical shell with stress-free top and no-slip bottom boundaries,
     The 12th Symposium of SEDI, Study of the Earth's Deep Interior, at the University of California at Santa Barbara, California, USA, in the Corwin Pavilion, from July 18 to 23, 2010
** 国内
   - _佐々木 洋平_,  石岡 圭一, 竹広 真一, 中島 健介, 石渡 正樹, 林 祥介, 2017:
     高速回転する薄い球殻内の熱対流により生成される表層縞帯状構造の消滅
     気象学会 2017年秋季大会
   - _佐々木 洋平_,  石岡 圭一, 竹広 真一, 中島 健介, 石渡 正樹, 林 祥介, 2017:
     高速回転する薄い球殻内の熱対流により生成される表層縞帯状構造の消滅
     第142回 地球電磁気･地球惑星圏学会, 総会・講演会(2017年 秋学会)
   - _佐々木 洋平_,  石岡 圭一, 竹広 真一, 中島 健介, 石渡 正樹, 林 祥介, 2017:
     高速回転する薄い球殻内の熱対流により生成される表層縞帯状構造の消滅
     日本惑星科学会、2017年周秋季講演会
   - 竹広真一, 佐々木洋平, 2017:
     回転球殻ダイナモにより引き起こされる磁気流体擾乱の強い安定成層への貫入,
     2017 年日本流体力学会年会
   - 竹広真一, _佐々木洋平_, 2017:
     地球外核の上部安定成層に対する組成対流の貫入,
     日本地球惑星科学連合 2017 年大会
   - _佐々木洋平_, 竹広真一，石渡正樹，山田道夫, 2017:
     回転球殻内の非弾性熱対流の臨界モードに対する熱拡散係数の動径分布の影響,
     日本地球惑星科学連合 2017 年大会
   - 竹広真一, 佐々木洋平, 2017:
     地球外核の上部安定成層に対する組成対流の貫入,
     新学術領域「核ーマントルの相互作用と共進化」成果報告会
   - 佐々木洋平, 竹広真一, 石渡正樹, 山田道夫 2016:
     回転球殻内の非弾性熱対流の臨界モードに対する熱拡散係数の動径分布の影響,
     2016年日本流体力学会年会
   - 竹広真一, 佐々木洋平 2016:
     回転球殻中の磁気対流により引き起こされる平均帯状流の外側安定成層への貫入.
     2016 年日本流体力学会年会
   - 竹広真一, 佐々木洋平, 2016:
     回転球殻中の磁気対流により引き起こされる平均帯状流の外側安定成層への貫入.
     日本地球惑星科学連合 2016 年大会, 2016 年 5 月 23 日,
     幕張メッセ国際会議場 講演セッション (講演番号: MIS10-P05)
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2016:
     高速回転する薄い球殻内の熱対流により生成される表層縞状構造への力学的境界条件の影響.
     日本地球惑星科学連合 2016 年大会
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2016:
     高速回転する薄い球殻内の熱対流により引き起こされる表層縞状構造の消滅,
     2016 年日本天文学会春季大会, 2016 年 3 月 15日, 首都大学東京 (講演番号 Z322b)
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2016:
     高速回転する薄い球殻内の熱対流により生成される表層縞状構造への力学的境界条件の影響.
     惑星大気研究会「水惑星」 2016 年 3 月 10 日, 神戸大学惑星科学研究センター
   - 竹広真一, 佐々木洋平, 石岡圭一, 2016:
     高速回転する薄い球殻内の熱対流により引き起こされる表層縞状構造への力学的境界条件の影響,
     平成 27 年度地球シミュレータ利用報告会, 2016 年 3 月 11 日 (金), コクヨホール
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2016:
     高速回転する薄い球殻内の熱対流により生成される表層縞状構造への力学的境界条件の影響.
     2016 年春季気象学会
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2015:
     高速回転する薄い球殻内の熱対流により引き起こされる表層縞状構造の消滅.
     2015 年日本流体力学会年会, 東工大大岡山キャンパス
   - 佐々木洋平, 竹広真一, 2015:
     回転球殻ダイナモにより引き起こされる磁気流体擾乱の強い安定成層への貫入.
     日本地球惑星科学連合 2015 年大会.
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2015:
     高速に回転する薄い球殻内の熱対流により引き起こされる表層縞状構造の消滅.
     日本地球惑星科学連合 2015 年大会.
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2015:
     高速に回転する薄い球殻内の熱対流により引き起こされる表層縞状構造の消滅.
     2015 年 日本気象学会春季大会
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2014:
     高速回転する薄い球殻中の対流により引き起こされる表層の帯状流,
     日本気象学会 2014 年度秋季大会, 福岡国際会議場
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2014:
     高速回転する薄い球殻内の熱対流により引き起こされる表層の帯状流,
     2014 年日本流体力学会年会, 2014 年 9 月 15 日, 東北大学川内北キャンパス
   - 佐々木洋平, 竹広真一, 石岡圭一, 中島健介, 林祥介, 2014:
     高速に回転する薄い球殻内の熱対流により引き起こされる表層の帯状流,
     日本地球惑星科学連合 2014 年大会, 2014年5月1日(木), 講演番号 PCG38-01
   - 竹広真一, 佐々木洋平, 林祥介, 山田道夫, 2013:
     回転球殻内の熱対流による角運動量輸送と太陽差分回転について,
     2013 年日本流体力学会年会 2013 年 9 月 13 日 東京農工大学
   - 佐々木洋平, 竹広真一, 中島 健介, 林祥介, 2013:
     回転球殻内の非弾性流体熱対流の線型安定性,
     2013 年日本流体力学会年会 2013 年 9 月 13 日, 東京農工大学
   - 佐々木 洋平, 竹広 真一, 中島 健介, 林 祥介, 2013:
     恒星・ガス惑星・氷惑星内部を念頭においた非弾性球殻対流モデル,
     日本地球惑星科学連合 2013 年大会 2013 年 5 月 20 日: 幕張メッセ国際会議場.
   - 竹広真一, 佐々木洋平, 林祥介, 山田道夫 2013:
     回転球殻内の熱対流によって引き起こされる差分回転と角運動量輸送.
     2013 年日本天文学会春季大会, 2013 年 3 月 22 日, 埼玉大学.
   - 佐々木洋平, 竹広真一, 2013:
     ガス惑星を念頭に置いた回転球殻対流,
     系外惑星大気ワークショップ 2013 年 3 月 4 - 5 日, 東京大学
   - Shin-ichi Takehiro, Yoshiyuki O. Takahashi, Ko-ichiro Sugiyama, Masatsugu Odaka, Masaki Ishiwatari, Youhei Sasaki, Seiya Nishizawa, Keiichi Ishioka, Kensuke Nakajima, Yoshi-Yuki Hayashi, 2013:
     Construction of Hierarchical Models for Fluid Dynamics in Earth and Planetary Sciences : DCMODEL project,
     惑星大気小研究会, 2013 年 2 月 5 日, 惑星科学研究センター
   - _佐々木洋平_, 竹広真一, 中島健介, 林祥介, 2012:
     薄い回転球殻対流により引き起こされる表層の帯状流,
     日本惑星科学会 2012年度秋季講演会,
     2012年 10 月 25 日, 神戸大学統合研究拠点
   - _佐々木 洋平_, 竹広 真一, 西澤 誠也, 林 祥介, 2012:
     階層的地球流体スペクトルモデル集 SPMODEL を用いた 惑星磁場ダイナモ計算
     第132回 SGEPSS総会および講演会,
     2012 年 10 月 23 日 (火), 札幌コンベンションセンター
   - _佐々木 洋平_, 竹広 真一, 中島 健介, 林 祥介, 2012:
     薄い回転球殻対流により引き起こされる表層の帯状流,
     日本気象学会 2012 年度秋季大会,
     2012 年 10 月 3 日, 北海道大学学術交流会館(講演番号 C168)
   - 竹広 真一, _佐々木 洋平_, 中島 健介, 林 祥介, 2012 :
     熱フラックス固定条件下での高速回転する円筒内の熱対流の線形安定性に対するエクマン摩擦の影響,
     日本流体力学会年会2012, 2012 年 9 月 17 日, 高知大学朝倉キャンパス
   - _佐々木 洋平_, 竹広 真一, 中島 健介, 林 祥介, 2012 :
     薄い回転球殻対流により引き起こされる表層の帯状流,
     日本流体力学会年会2012, 2012 年 9 月 16 日, 高知大学朝倉キャンパス
   - _佐々木 洋平_, 竹広 真一, 中島 健介, 林 祥介, 2012:
     恒星・ガス惑星の深部大気対流モデルの構築,
     日本地球惑星科学連合 2012 年大会, 講演番号JP-PS21
   - _佐々木 洋平_, 竹広 真一, 西澤 誠也, 中島 健介, 林 祥介, 2012:
     回転球殻ダイナモに対する緯度方向不均一な内側浮力フラックス境界条件の影響.
     日本地球惑星科学連合 2012 年大会., 講演番号JS-EM21
   - 高橋 芳幸, 杉山 耕一朗, 小高 正嗣, 石渡 正樹, _佐々木 洋平_, 西澤誠也, 中島 健介 竹広 真一, 林 祥介, 2011:
     共通のプログラムスタイルを持つ大気大循環モデルと雲解像モデルの開発,
     日本惑星科学会 2011 年秋季講演会, 2011 年 11 月 25 日, 相模女子大学翠葉会館 (講演番号 S32-06).
   - 高橋 芳幸, 杉山耕一朗, 小高 正嗣, 石渡 正樹, _佐々木 洋平_, 西澤 誠也, 中島 健介, 竹広 真一, 林 祥介, 2011:
     惑星大気計算のための大循環モデルならびに雲解像モデルの構築,
     日本気象学会 2011 年度秋季大会, 2011 年 11 月 16 日, 名古屋大学東山キャンパス (講演番号 D111).
   - 竹広 真一, _佐々木 洋平_, 西澤 誠也, 中島 健介, 林 祥介, 2011 :
     回転球殻ダイナモに対する緯度方向不均一な内側浮力フラックス境界条件の影響,
     日本流体力学会年会 2011, 2011 年 9 月 7 日, 首都大学東京南大沢キャンパス.
   - _佐々木 洋平_, 竹広 真一, 倉本 圭, 林 祥介, 2011:
     回転球殻MHDダイナモの初期磁場依存性,
     日本地球惑星科学連合 2011 年大会, 2011 年 5 月 26 日, 幕張メッセ国際会議場 (講演番号 S-EM36).
   - _佐々木 洋平_, 竹広 真一, 2011:
     熱フラックス固定境界条件下での回転球殻熱対流の線形安定性解析,
     日本地球惑星科学連合 2011 年大会, 2011 年 5 月 22 日, 幕張メッセ国際会議場 (講演番号 MIS021-P02)
   - _佐々木 洋平_, 竹広 真一, 林 祥介, 2010:
     回転球殻 MHDダイナモにおける上部力学的境界条件の影響,
     国立天文台 CfCAユーザーズミーティング, 2010 年 1 月 12 ～ 13 日, 国立天文台三鷹キャンパス.
   - _佐々木 洋平_, 竹広 真一, 林 祥介, 2008:
     回転球殻 MHD ダイナモにおける力学的境界条件の影響
     国立天文台 CfCA ユーザーズミーティング, 2008 年 12 月 17日, 国立天文台三鷹キャンパス.
   - _佐々木 洋平_, 竹広 真一, 林 祥介, 倉本 圭, 2008:
     下端に粘着条件・上端に応力無し条件を課した回転球殻 MHD ダイナモ計算,
     日本地球惑星科学連合 2008 年大会, 2008 年 5 月 28 日, 幕張メッセ国際会議場, 講演番号: E111-011
   - _佐々木 洋平_, 小高 正嗣, 林 祥介, 竹広 真一, 2004:
     ダイナモベンチマーク・ケース1 における磁場生成維持機構の解析,
     地球惑星科学関連学会 2004年合同大会, 2004 年 5 月 12 日, 幕張メッセ国際会議場, 講演番号: E012-004
   - _佐々木 洋平_, 竹広真一, 林祥介, 2002:
     回転球殻 MHD ダイナモの数値モデルの構築,
     理論天文学懇談会, 2002 年 12 月 24日(火) - 26 日(木), 国立天文台三鷹キャンパス
* 教育
  - 2017:
    - 京都大学 情報基礎[理学部](後期開講) 担当(分担)
    - 摂南大学 微積分 II[理工学部](前期開講) 担当
    - 摂南大学 微積分 I[理工学部](後期開講) 担当
  - 2016:
    - 京都大学 情報基礎[理学部](後期開講) 担当(分担)
    - 摂南大学 数学基礎I, II[経営学部](通年) 担当
    - 摂南大学 微積分 II[理工学部](前期開講) 担当
  - 2015:
    - 京都大学 情報基礎[理学部](後期開講) 担当(分担)
    - 摂南大学 数学基礎I, II[経営学部](通年) 担当
    - 摂南大学 微積分 II[理工学部](前期開講) 担当
  - 2014:
    - 京都大学 情報基礎[理学部](後期開講) 担当(分担)
    - 摂南大学 数学基礎I, II[経営学部](通年) 担当
    - 摂南大学 微積分 II[理工学部](前期開講) 担当
  - 2013:
    - 京都大学 情報基礎[理学部](後期開講) 担当(分担)
    - 摂南大学 数学基礎I, II[経営学部](通年) 担当
    - 摂南大学 微積分 II[理工学部](前期開講) 担当
  - 2012:
    - 京都大学 情報基礎[理学部](後期開講) 担当(分担)
    - 摂南大学 数学基礎I, II[経営学部](通年) 担当
  - 2011:
    - 京都大学 情報基礎[理学部](後期開講) 担当
* その他
** 雑誌記事
   - _佐々木洋平_, 2013:
     Ruby in Debian (2),
     Software Design 2013年10月号「Debian Hot Topics」,
     技術評論社
   - _佐々木洋平_, 2013:
     Ruby in Debian (1),
     Software Design 2013年9月号「Debian Hot Topics」,
     技術評論社
   - _佐々木 洋平_, 2012:
     Offlineimap + Dovecot で快適メール環境,
     Ubuntu Weekly Recipe 第247回,
     [[http://gihyo.jp/admin/serial/01/ubuntu-recipe/0247]]
   - _佐々木 洋平_, 2012:
     Debian - Debian の魅力と特徴,
     Software Design 2012年2月号, 第2特集「あなたをもっと自由にする OS - Debian を使い倒せ!」
     技術評論社
