#+TITLE: My Repository@Github
#+DATE: 2017-01-15 19:52:52
#+LANGUAGE: ja
#+REF: software
#+LAYOUT: default
#+SETUPFILE: ../_setup.org
#+PERMALINK: /software/index.html
* これは何?
  主に自分が使うために作成したソフトウェア、
  ひきとったソフトウェア、
  プレゼン用のテーマなどです.
  公開できるモノについては github にどんどん置いています. パッチウェルカム.
* [[file:rdtool/index.org][RDtool: formatter for RD]]
  RD は Ruby における POD(Plain Old Documentation) のようなものです.
  RDtool は RD のフォーマッタであり, RD を HTML や roff などに変換できます.
  以前は Moonwolf さんがリリースマネジメントをされていましたが,
  2011年 5 月に引き継いで, gem 化したりイロイロ弄っています.
* [[file:rail/index.org][Rail: Replace Agent-string Internal Library]]
  しまだみつひろさんが作成された rail を勝手に引き取って公開/気がついた時にアップデートしています.
  お気付きの点がありましたら, ご連絡下さい.
* [[file:tdiary-style-org/index.org][TDiary::Style::Org]]
  TDiary::Style::Org は
  [[http://orgmode.org/][Org-mode]] の syntax で
  [[http://www.tdiary.org/][tDiary.org]] の記事を書くためのスタイルを提供します．
* [[file:jekyll-org-converter/index.org][Jekyll Org Converter]]
  Jekyll の原稿として [[http://orgmode.org/][Org mode]] で書かれたファイルを処理できるようにするプラグインです．
  org ファイルの =+OPTIONS= を Jekyll の YAML Front Matter として扱える様にしてあります．
