#+TITLE: i3 の設定
#+DATE: 2017-09-29 16:16:04
#+LANGUAGE: ja
#+REF: cc-env/Debiani3
#+LAYOUT: cc-env
#+SETUPFILE: ~/Public/_setup.org
#+PERMALINK: /cc-env/Debiani3.html
Related [[wiki:index][Index]] [[id:591f6b0d-55ff-48eb-b095-401cdfa0d536][Debian]]
* 始めに

  スペックがあまり潤沢ではない機材を使うため,
  軽量な wm として [[https://i3wm.org/][i3 - improved tiling wm]] を使い始めた.

  元々常に tmux を全画面にして作業しているわけで
  タイル型である恩恵を受けられるのか, という疑問はあったのだが,
  使ってみたら「綺麗」かつ「驚きの軽さ」ということで, すっかり気にいってしまった.

* i3 と一緒に使っているもの

  とりあえず現状では以下:
  - ターミナル関連: urxvt と tmux → [[wiki:Terminal.org][Terminal生活]]
  - ファイルマネージャ: ranger
  - ブラウザ: firefox + vimfx
  - 外付けドライブの管理: udiskie
  - ランチャ: rofi

  他にも
  - Compositor: compton
  - ネットワーク: Network Manager
  - Bluetooth: blueman
  - 音: pulseaudio
  といった所はそのまま, かな?

  - これから試す/探しているモノ [0/2]
    - [ ] [[https://01.org/connman][ConnMan | 01.org]] も試してみたいが, どうだろう.
    - [ ] pulseaudio の CUI なミキサーって良い奴無いかなぁ...

* i3 の設定
  設定ファイルは末尾に掲載している.
** xdg-open と run-mailcap
  いわゆる GNOME や KDE といった Desktop 環境ではないので,
  たとえば =xdg-open= の挙動が変わります.
  それ自体は問題無いのですが, =~/.mailcap= の設定次第では
  =run-mailcap= が =xdg-open= を呼び, =xdg-open= が =run-mailcap= を呼び, といった
  無限ループが発生します.
  +run-mailcapを抜けば良い, という話もありますが, これ=mime-support=パッケージで提供されているので, 抜くとpython が抜けて大変な目に会います+

  というわけで, 安直には =xdg-open= を修正すれば良いですね:
  #+BEGIN_SRC diff
--- /usr/bin/xdg-open.orig	2015-10-06 04:19:48.000000000 +0900
+++ /usr/bin/xdg-open	2017-07-24 21:18:32.191564009 +0900
@@ -787,20 +787,9 @@
         if [ -n "$DISPLAY" ]; then
             filetype=`xdg-mime query filetype "$file" | sed "s/;.*//"`
             open_generic_xdg_mime "$file" "$filetype"
-        fi
-
-        if which run-mailcap 2>/dev/null 1>&2; then
-            run-mailcap --action=view "$file"
-            if [ $? -eq 0 ]; then
-                exit_success
-            fi
-        fi
-
-        if [ -n "$DISPLAY" ] && mimeopen -v 2>/dev/null 1>&2; then
-            mimeopen -L -n "$file"
-            if [ $? -eq 0 ]; then
-                exit_success
-            fi
+        else
+            echo "can't handle: please set mime type via xdg-mime"
+            exit_failure_operation_failed
         fi
     fi

  #+END_SRC

  あと, =~/.local/share/applications/mimeapps.list= から =~/.config/mimeapps.list= へ
  symbolic link を作成しておきます.
** Alt+Tab でのフォーカスの切り替え
   =i3-msg -t get_tree= で状態が json で出力されるので,
   これを parse して良きに図らえば良い.

   幾つか候補はあるけれど, 依存が少なくシンプルだったので
   [[https://github.com/westurner/i3t][westurner/i3t: i3t]] をありがたく使わせて頂くことに.

   設定は
   #+BEGIN_SRC conf-space
set $i3t_alt_tab ~/.config/i3/i3t.py n
bindsym $Alt+Tab exec $i3t_alt_tab
   #+END_SRC
   みたいな感じで良い.
** Rofi: ランチャ
   [[https://davedavenport.github.io/rofi/][Rofi]] は良い感じのランチャ.
   公式 Web の =This site is currently looking for a maintainer.= が怖いけれど.

   設定ファイルは =~/.config/rofi/config= か =~/.Xresources= で行なう.
   今はこんな塩梅:

#+INCLUDE: ~/.config/rofi/config src conf-xdefaults

   i3の方では Alt+F2, Alt+Shift+Tab で呼び出せるようにしている:
   #+BEGIN_SRC conf-space
bindsym $Alt+F2 $execi sh -c "rofi -show combi"
bindsym $Alt+Shift+Tab $execi sh -c "rofi -show window"
   #+END_SRC
** i3bar
   conky で情報を更新/整形して出力している.
   conky の設定は以下: =~/.config/i3/i3bar-conkyrc=

#+INCLUDE: ~/.config/i3/i3bar-conkyrc src lua

   呼び出しは =run-conky.sh= で:

#+INCLUDE: ~/.config/i3/run-conky.sh src sh

   status ラインは以下の通り
   #+BEGIN_SRC conf-space
# status bar
bar {
    position    top
    tray_output primary
    tray_padding -2
    font xft:FontAwesome,RictyDiminished 11.5
    status_command $HOME/.config/i3/i3bar-conky.sh
    colors {
      background #111822
      statusline #F6F3E8
      separator  #111822
      focused_workspace  #111822 #222244 #F6F3E8
      active_workspace   #555555 #555555 #F6F3E8
      inactive_workspace #020202 #242424 #888888
      urgent_workspace   #A00000 #900000 #F6F3E8
      binding_mode       #A00000 #900000 #f6f3e8
    }
}
   #+END_SRC
** screen lock: i3lock の設定
   suspend → resume した時に i3lock を走らせたいので
   =/etc/systemd/system/i3lock.service=:

#+INCLUDE: /etc/systemd/system/i3lock.service src systemd

   を作成して有効にしておく.
   本当は =~/.config/systemd/user= で設定したいのだけれど,
   権限が無いのか上手くいかない. polkit を適宜設定すれば良いのかもしれないけれど.
* i3 の設定ファイル
  設定ファイル全体は以下の通り

#+INCLUDE: ~/.config/i3/config src conf-space
