#+TITLE: Aptの設定
#+DATE: 2017-01-22 18:54:15
#+LANGUAGE: ja
#+REF: cc-env/DebianApt
#+LAYOUT: cc-env
#+SETUPFILE: ~/Public/_setup.org
#+PERMALINK: /cc-env/DebianApt.html
Related [[wiki:index][Index]]
* 始めに
  apt は非常に便利です. etch 以降から
  - パッケージのリストの差分だけをダウンロードする様になった.
  - secure-apt という機能が追加: [[http://kmuto.jp/d/index.cgi/debian/apt-secure.htm][KeN's GNU/Linux Diary|secure apt]] などを参考に.
    - 要するに「Release ファイルの GPG 署名を検証するよ」という話.
* apt の pin 止め

  特定のパッケージを {testing|unstable|experimental} から借りたい,
  とかいう場合には =/etc/apt/preferences= にその設定を書いておく.
  例えば以下の通り.
  #+BEGIN_EXAMPLE
    Package: *
    Pin: release a=experimental
    Pin-Priority: 90
  #+END_EXAMPLE

  Pin-Priority については以下を参照

| Pin-Priority |                                                           |
|            0 | install しない                                            |
|         1-99 | 指定すれば install できるが update の対象にならない       |
|          100 | 現在 install されているパッケージの Priority              |
|        (500) | 現在 install されていないパッケージの Priority            |
|        (989) | apt-pin の default                                        |
|          990 | apt-get の target-release が指定されている場合の Priority |
|    1000 以上 | ダウングレードしても, そのパッケージを install する.      |


上の例では 90 なので,
「指定すれば install できるが update の対象にはならない」状態.
もちろん依存関係は満たされていなければ, install はできない.
* apt-key への鍵の追加
  鍵は /etc/apt/trustdb.gpg に登録されている.
  #+BEGIN_EXAMPLE
    % sudo  apt-key list
  #+END_EXAMPLE
  で登録済みの鍵を確認できる.

  GPG 鍵の取得, export, import はそれぞれ
  #+BEGIN_EXAMPLE
    % gpg --keyserver [鍵サーバ] --recv-keys [鍵のID]
    % gpg --export  -a [鍵ID] > key_file
    % sudo apt-key add key_file
  #+END_EXAMPLE
  みたいに.

  鍵の登録は
  #+BEGIN_EXAMPLE
    % gpg --armor --export [鍵ID] | sudo apt-key add -
  #+END_EXAMPLE
  みたいしても良いかと.
* 現在の sources.list
  #+BEGIN_SRC conf
#
# Official
#
deb http://ftp.jp.debian.org/debian/ sid main non-free contrib
deb-src http://ftp.jp.debian.org/debian/ sid main non-free contrib
deb http://ftp.jp.debian.org/debian/ experimental main
deb-src http://ftp.jp.debian.org/debian/ experimental main
# UnOfficial
#
# Multimedia
# GPG: deb-multimedia-keyring
#
deb http://www.deb-multimedia.org sid main non-free
deb-src http://www.deb-multimedia.org sid main non-free
#
# Dennou
# GPG: 891D7E07
deb http://dennou-k.gfd-dennou.org/arch/cc-env/debian-dennou sid main
  #+END_SRC
* apt の便利ツール
  - apt-cache
  - apt-show-versions
  - apt-listchanges
  - apt-listbugs
  そのうち書く, かも.
* 参考文献
 - [[http://kmuto.jp/d/index.cgi/debian/apt-secure.htm][KeN's GNU/Linux Diary|secure apt]]
 - [[http://jaqque.sbih.org/kplug/apt-pinning.html][Apt-Pinning for Beginners]]
