#+TITLE: Squid で広告避け
#+DATE: 2017-02-20 18:55:06
#+LANGUAGE: ja
#+REF: cc-env/DebianSquid
#+LAYOUT: cc-env
#+SETUPFILE: ../_setup.org
#+PERMALINK: /cc-env/DebianSquid.html
Related [[wiki:index][Index]] [[id:591f6b0d-55ff-48eb-b095-401cdfa0d536][Debian]]

* はじめに

  手元で squid を上げています.

  最初は職場, 居室, モバイル等でネットワーク環境が変わる際に
  いちいちプロキシの設定を変えるとかやってられん, ということで
  - 手元で透過 proxy を立ち上げる
  - アプリケーションは常に proxy として localhost を見に行くようにする
  - ネットワーク接続の切り替え時に 上流の proxy を切り替える
  という目的で上げていました.

  それに加えて
  - そういえば squid って hosts ファイル読めたよね
  - 職場のプロキシが透過プロキシになってる
  ということで, これは広告避けにつかえるな, ということに.

  Web 広告については, まあ, いろんな意見があって良いと思います.
  邪魔にならない広告ならまあ良いんですけれど，
  - Flash とか mp4 で動画バリバリ
  - 閲覧中にポップアップ
  とか, そういう奴が多すぎます.
* 導入と設定
  導入
  #+BEGIN_EXAMPLE
% sudo apt-get install squid
  #+END_EXAMPLE
  apt 万歳

  現状の設定は以下の通り:
** 広告避けの host ファイル
   以下のスクリプトで適当に生成
#+INCLUDE: "/etc/squid/update-adaway-list.sh" src sh
   リストを保守して下さっている皆様に感謝.
** =/etc/squid/common.conf=
   昔プロキシを切り替えていた頃の名残で,
   上流を問わず全て同じ設定とする部分は =common.conf= に書いている.
   現状は
   - キャッシュはしない(した方が良いのかな...?)
   - 匿名化したいわけでも無いので, ヘッダは適当
   - 20080 番で動作
   といった所.
#+INCLUDE: "/etc/squid/common.conf" src conf
** =/etc/squid/squid.conf=
   中身は現状これだけ
#+INCLUDE: "/etc/squid/squid.conf" src conf
   もはや分割する意味が無い, とも言える.
** systemd と仲良く: =/etc/systemd/system/squid.service=
   キャッシュを動かす気も無いので子プロセスは生成されない.
   ということで, systemd 用の service ファイルを以下の様にでっち上げた.
#+INCLUDE: "/etc/systemd/system/squid.service" src conf
   あとは
#+BEGIN_EXAMPLE
% sudo systemctl daemon-reload
% sudo systemctl enable squid
% sudo systemctl start squid
#+END_EXAMPLE
   で快適. 適宜 =HTTP_PROXY= 等を設定しておくと良いだろう.
