#+DATE: 2017-07-25 21:18:33
#+TITLE: LightDM の設定
#+LANGUAGE: ja
#+REF: cc-env/DebianLightDM
#+LAYOUT: cc-env
#+SETUPFILE: ~/Public/_setup.org
#+PERMALINK: /cc-env/DebianLightDM.html
Related [[wiki:index][Index]] [[id:591f6b0d-55ff-48eb-b095-401cdfa0d536][Debian]]
* はじめに

  コンソールにログインして startx するのが楽で良いのだけれど,
  gnome-keyring ⇔ owncloud の連携がイマイチ上手くいかない様なので,
  しょうがなくログインマネージャとして [[https://www.freedesktop.org/wiki/Software/LightDM/][LightDM]] を使っている.

* 導入
  最近 [[https://tracker.debian.org/pkg/slick-greeter][Debian Package Tracker - slick-greeter]] なるモノも見つけたのだが
  今まで通り [[https://tracker.debian.org/pkg/lightdm-gtk-greeter][Debian Package Tracker - lightdm-gtk-greeter]] を使っている.
  #+BEGIN_EXAMPLE
% sudo apt-get install lightdm lightdm-gtk-greeter accountsservice
  #+END_EXAMPLE
  ログイン画面に個人の画像を表示したくて
  [[https://tracker.debian.org/pkg/accountsservice][Debian Package Tracker - accountsservice]] もインストールしていたりする.
* 設定
** ログイン画面に個人の画像を表示
   AccountsService で画像を表示するために
   =/var/lib/AccountsService/icons/= に
   96x96 の画像をユーザ名で置いておく
   #+BEGIN_SRC
% ls -la /var/lib/AccountsService/icons
合計 12
drwxr-xr-x 1 root root    14 2017-02-14 17:12 ./
drwxr-xr-x 1 root root    20 2017-02-13 16:55 ../
-rw-r--r-- 1 root root 11763 2017-02-14 17:12 uwabami
   #+END_SRC

   LightDM 本体の設定は =/etc/lightdm.conf= で.
   #+BEGIN_SRC conf
[Seat:*]
greeter-hide-users=false
   #+END_SRC
   を追加(もともとはコメントアウトされているので, それを =false= に変更)
** GTK Greeter の設定
   設定ファイルは =/etc/lightdm/lightdm-gtk-greeter.conf=: 今は以下の通り
   #+INCLUDE: "/etc/lightdm/lightdm-gtk-greeter.conf" src conf
   必要となるパッケージとしては
   - [[https://tracker.debian.org/pkg/fonts-ricty-diminished][Debian Package Tracker - fonts-ricty-diminished]]
   - [[https://tracker.debian.org/pkg/faenza-icon-theme][Debian Package Tracker - faenza-icon-theme]]
   かな.

   ついでに hiDPI かつ GTK3 Dark theme に対応するために
   =/usr/share/xgreeters/lightdm-gtk-greeter.desktop= を以下の通り修正
   #+INCLUDE: "/usr/share/xgreeters/lightdm-gtk-greeter.desktop" src conf

* その他, 気になる所
  - 幾つか気になる点があって, どうしたモンだかなぁ [0/2]
    - [ ] login,logout すると gnome-keyring-daemon が多重起動している気が.
      - これは PAM の設定次第なんだろうか.
      - まあ, 一度ログインしたら電源落とすまでログアウトしないよね, と言われれば
        そうなんだが.
    - [ ] =dm-tool lock= をうまく使えれば, 他の screensaver は不要かもしれない
      - もしくは =light-locker= を使えば良いのかな. =i3lock= の方が好みなんだが.
      - というか, lock してても =Ctrl+Alt+番号= で画面切り替わらない? もしかして.

  とはいえ, 総じてやりたいことはできているので, これで良いか, という気分ではある.
